name: AWS-Lambda-Layer-OSMTools CI-CD

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build Libraries
        run: bash ./build-libraries.sh
      - name: Test Libraries
        run: bash ./test-libraries.sh
      - uses: actions/upload-artifact@v4
        with:
          name: aws-lambda-layer-osmtools
          path: build/aws-lambda-layer-osmtools-*.zip
          if-no-files-found: error
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-2
    permissions:
      id-token: write
      contents: read
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: aws-lambda-layer-osmtools
      - name: Authenticate AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::106542751629:role/GitHubActions-AWSLambdaLayerOSMTools
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Publish Layer
        run: |
          aws s3 cp build/aws-lambda-layer-osmtools-base.zip s3://aws-lambda-layer-osmtools/aws-lambda-layer-osmtools-base.zip
          aws s3 cp build/aws-lambda-layer-osmtools-osmium.zip s3://aws-lambda-layer-osmtools/aws-lambda-layer-osmtools-osmium.zip
          aws s3 cp build/aws-lambda-layer-osmtools-osrm.zip s3://aws-lambda-layer-osmtools/aws-lambda-layer-osmtools-osrm.zip
          aws s3 cp build/aws-lambda-layer-osmtools-tilemaker.zip s3://aws-lambda-layer-osmtools/aws-lambda-layer-osmtools-tilemaker.zip
          
          export LAYER_VERSION_BASE=$(aws lambda publish-layer-version \
            --layer-name aws-lambda-layer-osmtools-base \
            --description "OpenStreetMap C++ tools (base layer) available as an AWS Lambda Layer!" \
            --compatible-runtimes "nodejs22.x" \
            --license-info "https://github.com/HankieCodes/aws-lambda-layer-osmtools/blob/main/LICENSE.txt" \
            --compatible-architectures "x86_64" \
            --content "S3Bucket=aws-lambda-layer-osmtools,S3Key=aws-lambda-layer-osmtools-base.zip" \
            --query "Version")
          export LAYER_VERSION_OSMIUM=$(aws lambda publish-layer-version \
            --layer-name aws-lambda-layer-osmtools-osmium \
            --description "OpenStreetMap C++ tools (osmium) available as an AWS Lambda Layer!" \
            --compatible-runtimes "nodejs22.x" \
            --license-info "https://github.com/HankieCodes/aws-lambda-layer-osmtools/blob/main/LICENSE.txt" \
            --compatible-architectures "x86_64" \
            --content "S3Bucket=aws-lambda-layer-osmtools,S3Key=aws-lambda-layer-osmtools-osmium.zip" \
            --query "Version")
          export LAYER_VERSION_OSRM=$(aws lambda publish-layer-version \
            --layer-name aws-lambda-layer-osmtools-osrm \
            --description "OpenStreetMap C++ tools (osrm and node-osrm) available as an AWS Lambda Layer!" \
            --compatible-runtimes "nodejs22.x" \
            --license-info "https://github.com/HankieCodes/aws-lambda-layer-osmtools/blob/main/LICENSE.txt" \
            --compatible-architectures "x86_64" \
            --content "S3Bucket=aws-lambda-layer-osmtools,S3Key=aws-lambda-layer-osmtools-osrm.zip" \
            --query "Version")
          export LAYER_VERSION_TILEMAKER=$(aws lambda publish-layer-version \
            --layer-name aws-lambda-layer-osmtools-tilemaker \
            --description "OpenStreetMap C++ tools (tilemaker) available as an AWS Lambda Layer!" \
            --compatible-runtimes "nodejs22.x" \
            --license-info "https://github.com/HankieCodes/aws-lambda-layer-osmtools/blob/main/LICENSE.txt" \
            --compatible-architectures "x86_64" \
            --content "S3Bucket=aws-lambda-layer-osmtools,S3Key=aws-lambda-layer-osmtools-tilemaker.zip" \
            --query "Version")
          
          aws lambda add-layer-version-permission \
            --layer-name aws-lambda-layer-osmtools-base \
            --version-number $LAYER_VERSION_BASE \
            --statement-id public-layer \
            --principal "*" \
            --action "lambda:GetLayerVersion"
          aws lambda add-layer-version-permission \
            --layer-name aws-lambda-layer-osmtools-osmium \
            --version-number $LAYER_VERSION_OSMIUM \
            --statement-id public-layer \
            --principal "*" \
            --action "lambda:GetLayerVersion"
          aws lambda add-layer-version-permission \
            --layer-name aws-lambda-layer-osmtools-osrm \
            --version-number $LAYER_VERSION_OSRM \
            --statement-id public-layer \
            --principal "*" \
            --action "lambda:GetLayerVersion"
          aws lambda add-layer-version-permission \
            --layer-name aws-lambda-layer-osmtools-tilemaker \
            --version-number $LAYER_VERSION_TILEMAKER \
            --statement-id public-layer \
            --principal "*" \
            --action "lambda:GetLayerVersion"
